# Use the official Maven image with OpenJDK 23
FROM maven:3.3.2-jdk-23 AS build

# Copy the project files to the container
COPY . .

# Run the working directory
RUN mvn clean package -DskipTests

# From the jar
FROM openjdk:23-jdk-slim

#Copy from the target file
COPY --from=build /target/gkQuestion-0.0.1-SNAPSHOT.jar gkQuestion.jar

#Exposing the directory file in the image
EXPOSE 8080

#Entry point for our application
ENTRYPOINT [ "java","-jar","gkQuestion.jar" ]